services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: traineros
      POSTGRES_PASSWORD: traineros
      POSTGRES_DB: traineros
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
